feat: added filter for modifying the isStarted for externally hosted …
openedx/openedx-filters pull request #106
Opened 2023-07-25 09:15 UTC by jajjibhai008

…courses

**Description:** Describe in a couple of sentences what this PR adds

**JIRA:** Link to JIRA ticket

**Dependencies:** dependencies on other outstanding PRs, issues, etc. 

**Merge deadline:** List merge deadline (if any)

**Installation instructions:** List any non-trivial installation 
instructions.

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer 
- [ ] tag reviewer 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

2023-07-27 09:19 UTC, jajjibhai008 commented
@felipemontoya could you please review my PR? I have to ship these changes as soon as possible.

2023-07-28 00:05 UTC, felipemontoya commented
Hi @jajjibhai008 , thanks for tagging me.

Do you have the link to the corresponding edx-platform pr? I am not understanding the goal of this filter by looking at the definition alone.

2023-07-28 00:15 UTC, muhammad-ammar commented
Hi @felipemontoya, Here is the edx-platform PR: https://github.com/openedx/edx-platform/pull/32788

2023-07-28 14:48 UTC, felipemontoya commented
Thanks a lot. Now I understand much better.

I think the definition of the filter is too specific to make it a reusable filter.
Also it makes the naming difficult.

You have:
"org.openedx.learning.course.is.started.creation.started.v1"

But in order to truly pinpoint the filtered situation it would have to be:
"org.openedx.learning.home.enrollment.api.render.is.started.calculated.v1"

I think you could refactor this a bit to make it global to the whole API call.

Broadly speaking you could let the serializer run its whole logic and then add a filter that lets you work on the final result.

```python
class EnrollmentSerializer(serializers.Serializer):

    def to_representation(self, instance):
        """Let the filter work after the whole instance is serialized"""
        ret = super().to_representation(instance)
        ret = CourseEnrollmentAPIRendered().run_filter(representation=ret)
        return ret
```

So you could have a filter whose domain is:
"org.openedx.learning.home.enrollment.api.rendered.v1"

Such a filter could be re used in the future when you want to alter any of the fields of this API

2023-07-28 14:50 UTC, felipemontoya commented
Now that I think of it, maybe you would rather filter the instance object before is passed to `to_representation`. In that case you are working with actual models instead of text/json in the filter. But the overall idea stays the same.

2023-07-28 15:03 UTC, felipemontoya requested changes
as per the comment above

2023-07-29 04:57 UTC, jajjibhai008 commented
> Thanks a lot. Now I understand much better.
> 
> I think the definition of the filter is too specific to make it a reusable filter. Also it makes the naming difficult.
> 
> You have: "org.openedx.learning.course.is.started.creation.started.v1"
> 
> But in order to truly pinpoint the filtered situation it would have to be: "org.openedx.learning.home.enrollment.api.render.is.started.calculated.v1"
> 
> I think you could refactor this a bit to make it global to the whole API call.
> 
> Broadly speaking you could let the serializer run its whole logic and then add a filter that lets you work on the final result.
> 
> ```python
> class EnrollmentSerializer(serializers.Serializer):
> 
>     def to_representation(self, instance):
>         """Let the filter work after the whole instance is serialized"""
>         ret = super().to_representation(instance)
>         ret = CourseEnrollmentAPIRendered().run_filter(representation=ret)
>         return ret
> ```
> 
> So you could have a filter whose domain is: "org.openedx.learning.home.enrollment.api.rendered.v1"
> 
> Such a filter could be re used in the future when you want to alter any of the fields of this API

HI @felipemontoya Thanks for your detailed review.

1) I think your suggested filter name is more concise and descriptive, So I have renamed the filter name in all PRs.
2) I agree with your approach to writing the filtration logic in the `to_representation(self, instance)` method. This will make code more efficient and readable. I have update the[ platform PR](https://github.com/openedx/edx-platform/pull/32788) according to your suggestions. 
Please let me know if you have any questions or confusion.

2023-08-01 01:59 UTC, felipemontoya requested changes
hey @jajjibhai008, I'm happy that the review helped.

I'd still like to understand something. You changed the position of the filter to a position where you can have an effect on [all the fields](https://github.com/openedx/edx-platform/pull/32788/files#diff-bdf2cf3efb3de96e4fe1df13d5f90e685dc7d4c0e3c3fd61c4e7424e2feb8abcL192-L203) for this API. But you are still defining the filter in a way that would only let a developer using the filter change the `is_started` value. I would still suggest that you change the definition so that by opening the capability to alter the API you are actually allowing the complete set of fields to be worked on.

Then you could call the filter `"org.openedx.learning.home.enrollment.api.rendered.v1"` and allow other features in the future to build on top of this.

2023-08-01 06:29 UTC, jajjibhai008 commented
> hey @jajjibhai008, I'm happy that the review helped.
> 
> I'd still like to understand something. You changed the position of the filter to a position where you can have an effect on [all the fields](https://github.com/openedx/edx-platform/pull/32788/files#diff-bdf2cf3efb3de96e4fe1df13d5f90e685dc7d4c0e3c3fd61c4e7424e2feb8abcL192-L203) for this API. But you are still defining the filter in a way that would only let a developer using the filter change the `is_started` value. I would still suggest that you change the definition so that by opening the capability to alter the API you are actually allowing the complete set of fields to be worked on.
> 
> Then you could call the filter `"org.openedx.learning.home.enrollment.api.rendered.v1"` and allow other features in the future to build on top of this.


@felipemontoya I have updated the filter definition to `"org.openedx.learning.home.enrollment.api.rendered.v1"`.

2023-08-02 00:00 UTC, felipemontoya requested changes

2023-08-02 00:00 UTC, felipemontoya commented on openedx_filters/learning/filters.py
> +class CourseEnrollmentRenderStarted(OpenEdxPublicFilter):
If you decide to change like the comment below, I would also ask to please change the name to `CourseEnrollmentAPIRenderStarted` so that it is clear that the render is at an API.

2023-08-02 03:24 UTC, jajjibhai008 commented on openedx_filters/learning/filters.py
> +class CourseEnrollmentRenderStarted(OpenEdxPublicFilter):
@felipemontoya i have updated the `to_representation(self, instance)` of enrollment_serializer in edx-platform and updated the filter definition to `CourseEnrollmentAPIRenderStarted`.
Please have a look at them and let me know of any further changes.

2023-08-02 03:42 UTC, felipemontoya approved these changes
Thanks @jajjibhai008. I would say codewise this looks good now.

I don't have access to any of the Jira tickets you linked so I have no Idea about how this fullfills or not the requirement, but I'll leave my review approval

2023-08-02 03:52 UTC, jajjibhai008 commented
> 
Thanks, @felipemontoya for your kind and experienced reviews.
As I don't have access to merge it, please merge it for me, so that I can use these changes.

2023-08-02 03:57 UTC, felipemontoya commented
Could someone else from your team that has access to the jira tickets give a review as well? I have no context from the requirements other that what is in this page.

2023-08-02 06:17 UTC, muhammad-ammar approved these changes
Awesome Work!

2023-08-02 14:57 UTC, merged