feat: add filter for hooking XBlock Render
openedx/openedx-filters pull request #171
Opened 2024-05-28 17:55 UTC by nsprenkle

⚠️ DRAFT in architecture review.

**Description:** Add a filter just before rendering of an XBlock scope.

**Justification:** Some of our current work requires an ability to read and modify data in the XBlock render pipeline. While there *already* exist filters in the Vertical rendering pipeline, these are limited compared to the XBlock rendering pipeline in 2 important ways.

1. The vertical render does not have access to the original request object, meaning if we are otherwise unable to read/modify data on or in response to that request.
2. The vertical render pipeline does not apply to XBlock scopes outside of vertical/unit. If, for example, we ask to render an individual block, these filters will not get activated.

**JIRA:** [AU-2039](https://2u-internal.atlassian.net/browse/AU-2039) and [2037](https://2u-internal.atlassian.net/browse/AU-2037)

**Merge deadline:** List merge deadline (if any)

**Installation instructions:** n/a

**Testing instructions:**

1. Check out related edx-platform branch: [nsprenkle/xblock-render-filter](https://github.com/openedx/edx-platform/tree/nsprenkle/xblock-render-filter)
4. Install local copy of `openedx-filters`.
5. Attempt to render an xblobk: `http://{lms}/xblock/block-v1:{block-id}?view=student_view
6. Verify filter step is run.

**Reviewers:**
- [ ] @ormsbee 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

2024-05-31 20:47 UTC, felipemontoya reviewed
The filter definition seems reasonable to me. Given the location you are planning to use the filter, it looks to me more similar to a `RenderXBlockCompleted`.
I left this comment at the commit you shared. https://github.com/openedx/edx-platform/commit/28e160108218c7f4c85f3fae84eb825d703c3a15#commitcomment-142615584

2024-06-03 18:52 UTC, nsprenkle commented
> The filter definition seems reasonable to me. Given the location you are planning to use the filter, it looks to me more similar to a `RenderXBlockCompleted`. I left this comment at the commit you shared. [openedx/edx-platform@28e1601#commitcomment-142615584](https://github.com/openedx/edx-platform/commit/28e160108218c7f4c85f3fae84eb825d703c3a15#commitcomment-142615584)



> The filter definition seems reasonable to me. Given the location you are planning to use the filter, it looks to me more similar to a `RenderXBlockCompleted`. I left this comment at the commit you shared. [openedx/edx-platform@28e1601#commitcomment-142615584](https://github.com/openedx/edx-platform/commit/28e160108218c7f4c85f3fae84eb825d703c3a15#commitcomment-142615584)

Have updated filter names per your suggestion.

2024-06-04 19:26 UTC, nsprenkle commented
@felipemontoya / @ormsbee , looking for re-review when you have time :)

2024-06-07 22:59 UTC, felipemontoya requested changes
The filter looks good, but in order to give users of this filter more range of action I suggest we allow them to render something controllable and not only a 500 error.

2024-06-07 22:59 UTC, felipemontoya commented on openedx_filters/learning/filters.py
> +    class PreventXBlockBlockRender(OpenEdxFilterException):
In a comment at the branch in edx-platform I commented about it being common behavior that we allow filter users to modify what is shown to students. https://github.com/openedx/edx-platform/commit/28e160108218c7f4c85f3fae84eb825d703c3a15#r142727965

Do you have a reason for not doing that? If you agree that this should be done I would suggest we create a second exception here similar to the AccountSettingRenderStarted filter does. https://github.com/openedx/openedx-filters/blob/0738e99c60cba48e36df3731200f9b34be04439c/openedx_filters/learning/filters.py#L53C1-L67C57

2024-06-10 20:06 UTC, nsprenkle commented on openedx_filters/learning/filters.py
> +    class PreventXBlockBlockRender(OpenEdxFilterException):
Ah, okay, I didn't realize that comment also applied here in the creation of a new exception. I'll go ahead and add that.

2024-06-10 20:46 UTC, nsprenkle commented on openedx_filters/learning/filters.py
> +    class PreventXBlockBlockRender(OpenEdxFilterException):
Have updated here and in edx-platform copy https://github.com/openedx/edx-platform/pull/34865/commits/6ba29598fc6ace373303ef7c889c062c85fac1ef

2024-06-10 20:47 UTC, nsprenkle commented
@felipemontoya , ready for re-review

2024-06-14 16:16 UTC, felipemontoya approved these changes
Brilliant. Thanks a lot @nsprenkle. I think the filter is ready.

@mariajgrimaldi correct me please if I'm wrong. To merge we need to do a minor bump and add the changelog, right?

such as with https://github.com/openedx/openedx-filters/pull/158/files

2024-06-14 16:20 UTC, mariajgrimaldi commented
@nsprenkle @felipemontoya: yes, that's all we need! Thank you both.

2024-06-14 19:17 UTC, felipemontoya approved these changes

2024-06-14 19:18 UTC, merged