Mjg/create a new filter
openedx/openedx-filters pull request #242
Opened 2024-12-25 14:34 UTC by mariajgrimaldi

## Description

Describe what this pull request changes, and why. Include implications for people using this change.
Design decisions and their rationales should be documented in the repo (docstring / ADR), per
[OEP-19](https://open-edx-proposals.readthedocs.io/en/latest/oep-0019-bp-developer-documentation.html), and can be
linked here.

Useful information to include:

- Motivation and context of the implementation
- What's the intended use of this change?
- Use cases and usage examples available

## Supporting information

Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions. Also, link to any relevant documentation useful for reviewers.
Be sure to check they are publicly readable, or if not, repeat the information here.

## Testing instructions

Please provide detailed step-by-step instructions for testing this change, including any necessary setup, e.g., additional requirements, plugins, configuration variables, etc, and environment details to ensure the reviewer can test the change.

## Deadline

"None" if there's no rush, or provide a specific date or event (and reason) if there is one.

## Other information

Include anything else that will help reviewers and consumers understand the change.

- Any other PRs or issues that should be linked here? Any related PRs?
- Any special concerns or limitations? For example: deprecations, security, or anything you think should be noted.

## Checklists

Check off if complete *or* not applicable:

**Merge Checklist:**
- [ ] All reviewers approved
- [ ] Reviewer tested the code following the testing instructions
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added with short description of the change and current date
- [ ] Documentation updated (not only docstrings)
- [ ] Code dependencies reviewed
- [ ] Fixup commits are squashed away
- [ ] Unit tests added/updated
- [ ] Noted any: Concerns, dependencies, migration issues, deadlines, tickets

**Post Merge:**
- [ ] Create a tag
- [ ] Create a release on GitHub
- [ ] Check new version is pushed to PyPI after tag-triggered build is
      finished.
- [ ] Delete working branch (if not needed anymore)
- [ ] Upgrade the package in the Open edX platform requirements (if applicable)

2024-12-25 14:34 UTC, openedx-webhooks commented
Thanks for the pull request, @mariajgrimaldi!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.


#### :radio_button: Update the status of your PR

Your PR is currently marked as a draft.  After completing the steps above, update its status by clicking "Ready for Review", or removing "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->


#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@openedx/hooks-extension-framework`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2025-01-06 12:59 UTC, sarina approved these changes

2025-01-06 12:59 UTC, sarina commented on docs/how-tos/create-a-pipeline-step.rst
> +Step 4: Create a Pipeline Step
This goes from step 2 to step 4!

2025-01-06 12:59 UTC, sarina commented on docs/how-tos/create-a-pipeline-step.rst
> +- Implement error handling and logging in the pipeline step to handle exceptions and provide useful information for debugging, considering both development and production environments.
Does it make sense to include an example of logging or verbose error messaging in your simple example above?

2025-01-06 12:59 UTC, sarina commented on docs/how-tos/create-a-pipeline-step.rst
> +In our example, you could write a unit test for the pipeline step like this:
Where should the unit tests live? (is it obvious or is it worth explaining?)

2025-01-06 12:59 UTC, sarina commented on docs/reference/architecture-subdomains.rst
> +| Analytics         | Provides insights into learner behavior and course performance.                                    |
```suggestion
| Analytics         | A look into learner behavior and course performance.                                    |
```

I don't love this but I think you should avoid using "insights" to not confuse with Insights, the deprecated analytics product.

2025-01-07 17:16 UTC, mariajgrimaldi commented on docs/how-tos/create-a-pipeline-step.rst
> +Step 4: Create a Pipeline Step
I totally missed this. Thank you!

2025-01-07 17:17 UTC, mariajgrimaldi commented on docs/how-tos/create-a-pipeline-step.rst
> +- Implement error handling and logging in the pipeline step to handle exceptions and provide useful information for debugging, considering both development and production environments.
I added some. This suggestion mainly focuses on helping developers understand when the filter is doing what it's supposed to do based on the given conditions. Do you think the example illustrates that?

2025-01-07 17:17 UTC, mariajgrimaldi commented on docs/how-tos/create-a-pipeline-step.rst
> +In our example, you could write a unit test for the pipeline step like this:
Totally! I added the path where the tests should be located.

2025-01-07 17:18 UTC, mariajgrimaldi commented on docs/reference/architecture-subdomains.rst
> +| Analytics         | Provides insights into learner behavior and course performance.                                    |
I used "visbility" instead of insights, what do you think?

2025-01-07 17:21 UTC, sarina approved these changes

2025-01-07 21:50 UTC, MaferMazu approved these changes
I have one suggestion, but the rest looks good to me.

Thanks @mariajgrimaldi ✨

2025-01-07 21:50 UTC, MaferMazu commented on docs/how-tos/create-a-pipeline-step.rst
> +- You have identified that you need to create a new filter and have a use case for the filter.
My only comment is that we may want to drop the last assumption because, in this doc, we are talking about pipelines, and you cover the understanding part in Step 1.

2025-01-07 23:28 UTC, MaferMazu commented on docs/how-tos/create-a-pipeline-step.rst
> +You should review the list of filters available in the Open edX platform and identify the filter that best fits your use case. In our example, we will use the `CourseEnrollmentStarted filter`_ to imp
```suggestion
You should review the `list of filters available`_ in the Open edX platform and identify the filter that best fits your use case. In our example, we will use the `CourseEnrollmentStarted filter`_ to implement the logic for our use case. You should review the filter's arguments to understand the data that will be passed to the pipeline step and the expected output. This will help you define the pipeline step's logic and signature.
```

I added this suggestion because I saw something similar in the openedx-events PR, and it took me to Reference/Events. I didn't know that page existed. I think it should be helpful to be able to redirect the people to the list of filters here: https://docs.openedx.org/projects/openedx-filters/en/latest/reference/filters.html#

Note: In the suggestion, we need to reference the link because I didn't put it.

2025-01-08 14:15 UTC, mariajgrimaldi commented on docs/how-tos/create-a-pipeline-step.rst
> +- You have identified that you need to create a new filter and have a use case for the filter.
Thanks for the suggestion! I replaced this line with understanding the pipeline step logic to implement instead: https://github.com/openedx/openedx-filters/pull/242/commits/667abe5c079d70fe34b9369c6b1880fefa54c6d3

2025-01-08 14:15 UTC, mariajgrimaldi commented on docs/how-tos/create-a-pipeline-step.rst
> +You should review the list of filters available in the Open edX platform and identify the filter that best fits your use case. In our example, we will use the `CourseEnrollmentStarted filter`_ to imp
This is pretty useful, thank you! https://github.com/openedx/openedx-filters/pull/242/commits/ad4a7946180a54a14424f5ff8b4a63e829cf6d0b

2025-01-09 15:26 UTC, MaferMazu commented
Thanks for addressing my feedback. This looks good to me ✅

2025-01-22 22:37 UTC, felipemontoya requested changes
Some inline comments. Overall looks good, but I'm starting to see something that we are doing rather unintentionally. By focusing our documentation effort on all the parts of the lifecycle of : creating a new filter that did not previously exist, add said filter to the platform, implement pipeline steps with your feature, we are creating the impression on devs that they all need to take this route. I think we need to make it very well known that there are already quite a few filters and events available and that for every one of those you only need the part where you develop your code. This misconception is pushing people to believe that using filters is too complicated and not worth doing.

2025-01-22 22:37 UTC, felipemontoya commented on docs/how-tos/create-a-new-filter.rst
> +   I want to add a filter that will be triggered when a user enrolls in a course from the course about page. This filter will be used to prfilter users from enrolling in a course if they do not meet
```suggestion
   I want to add a filter that will be triggered when a user enrolls in a course from the course about page. This filter will be used to prevent users from enrolling in a course if they do not meet the eligibility criteria. The filter will be triggered when the user clicks the enroll button on the course about page and will check if the user meets the eligibility criteria. If the user does not meet the criteria, the filter will raise an exception to prevent the user from enrolling in the course.
```

2025-01-22 22:37 UTC, felipemontoya commented on docs/how-tos/create-a-new-filter.rst
> +Implementing pipeline steps allows you to modify the behavior of the application when the filter is triggered. Pipeline steps are a sequence of steps that are executed in a specific order to modify t
I think we should say here that the pipeline steps are meant to be written in the plugin code and not in the openedx-filters library.

2025-01-22 22:37 UTC, felipemontoya commented on docs/how-tos/create-a-pipeline-step.rst
> +First, add the ``openedx-filters`` plugin into your dependencies so the library's environment recognizes the event you want to consume. You can install ``openedx-filters`` by running:
``openedx-filters`` plugin -> ``openedx-filters`` library. To not make it more confusing plugin should refer always to the developer's pluggable code and the openedx-filters or openedx-events should be called the library.

2025-01-22 22:37 UTC, felipemontoya commented on docs/how-tos/create-a-pipeline-step.rst
> +First, add the ``openedx-filters`` plugin into your dependencies so the library's environment recognizes the event you want to consume. You can install ``openedx-filters`` by running:
"so the library's environment recognizes the event you want to consume" this is also confusing. We are not consuming an event, but creating a filter pipeline in this guide.

2025-01-24 09:52 UTC, mariajgrimaldi commented
> Overall looks good, but I'm starting to see something that we are doing rather unintentionally. By focusing our documentation effort on all the parts of the lifecycle of : creating a new filter that did not previously exist, add said filter to the platform, implement pipeline steps with your feature, we are creating the impression on devs that they all need to take this route. I think we need to make it very well known that there are already quite a few filters and events available and that for every one of those you only need the part where you develop your code.

I hear what you're saying, but I’m not sure I follow, given that one of the first steps in creating a pipeline specifically mentions reviewing the list of available filters to identify the right one for the use case: https://docsopenedxorg--242.org.readthedocs.build/projects/openedx-filters/en/242/how-tos/create-a-pipeline-step.html#step-1-understand-your-use-case-and-identify-the-filter-to-use. Do you think that part isn’t clear enough? I’m open to suggestions to make it more obvious.

2025-01-24 09:55 UTC, mariajgrimaldi commented on docs/how-tos/create-a-new-filter.rst
> +   I want to add a filter that will be triggered when a user enrolls in a course from the course about page. This filter will be used to prfilter users from enrolling in a course if they do not meet
Thank you for noticing!

2025-01-24 10:14 UTC, mariajgrimaldi commented on docs/how-tos/create-a-new-filter.rst
> +Implementing pipeline steps allows you to modify the behavior of the application when the filter is triggered. Pipeline steps are a sequence of steps that are executed in a specific order to modify t
There is a note about it here: https://github.com/openedx/openedx-filters/pull/242/files#diff-f1e167403e1377f568c3a2641fb3a151cd61d26887b3a468f91669d4494aee61R57. But I agree adding it here could make it clearer.

2025-01-24 10:15 UTC, mariajgrimaldi commented on docs/how-tos/create-a-pipeline-step.rst
> +First, add the ``openedx-filters`` plugin into your dependencies so the library's environment recognizes the event you want to consume. You can install ``openedx-filters`` by running:
I borrowed this from the consume events docs, that's why it is all mixed up. Thank you for noticing! Although I now have a question, technically openedx-events _is_ a plugin, do you think that would cause misunderstandings? Calling openedx-events a plugin instead?

2025-01-24 10:28 UTC, mariajgrimaldi commented
@felipemontoya: I've addressed all your comments in this commit https://github.com/openedx/openedx-filters/pull/242/commits/2ee41e3af51e863fee70b0647c56c15cf899b56d. Thank you again!

2025-01-30 14:30 UTC, felipemontoya commented on docs/how-tos/create-a-pipeline-step.rst
> +First, add the ``openedx-filters`` plugin into your dependencies so the library's environment recognizes the event you want to consume. You can install ``openedx-filters`` by running:
What threshold do you use to recognize something as a plugin? For me the defining characteristic of a plugin, is that it defines the `plugin_app` in its apps.py config. Neither events nor filters do that. That is why I call them libraries.

I could certainly be picking the wrong definition here. The other approach that I use for this, which is what triggered the comment, is that plugin is something that is not part of the core. We try to gently push developers in the direction of using plugins for the  custom development instead of forking. By this approach also events and filters would not be considered plugins.

2025-01-30 16:29 UTC, mariajgrimaldi commented on docs/how-tos/create-a-pipeline-step.rst
> +First, add the ``openedx-filters`` plugin into your dependencies so the library's environment recognizes the event you want to consume. You can install ``openedx-filters`` by running:
Sorry for the misunderstanding. opened-events _is_ a Django application which makes it more than a library, and I thought it actually defined a ``plugin_app``, but after reviewing [apps.py](https://github.com/openedx/openedx-events/commit/29fc69e955b6bed941f069ab355ae63f07e37d2a) I realized it didn't.

2025-01-31 17:43 UTC, merged

2025-02-02 16:27 UTC, sarina commented
@mariajgrimaldi once again moving filenames has broken the docs.openedx.org build: https://readthedocs.org/projects/docsopenedxorg/builds/27044031/

Could you please either refrain from moving filenames further, or make a dummy pr to docs.openedx.org when moving filenames to ensure you're not breaking our build over there?

2025-02-02 19:33 UTC, mariajgrimaldi commented
@sarina: I'm sorry for breaking the build again. I missed it by accident.

This was the last docs PR that changed file names so I'm hoping this won't happen again.

I'll work on this first time tomorrow.