feat: add filters before registration and user setttings context
openedx/openedx-filters pull request #46
Opened 2022-11-15 23:29 UTC by Henrrypg

**Description:** Describe in a couple of sentences what this PR adds

**JIRA:** Link to JIRA ticket

**Dependencies:** dependencies on other outstanding PRs, issues, etc. 

**Merge deadline:** List merge deadline (if any)

**Installation instructions:** List any non-trivial installation 
instructions.

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer 
- [ ] tag reviewer 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

2022-11-15 23:29 UTC, openedx-webhooks commented
Thanks for the pull request, @Henrrypg!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-11-21 11:43 UTC, mariajgrimaldi commented
Hello! To contribute to this PR you'll have to sign a CLA first. cc @felipemontoya

2022-12-05 10:31 UTC, mariajgrimaldi requested changes
Hello! Thanks for your contribution. Can you please fix the CI checks?

2022-12-05 10:31 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +        return context
You'll need to create a test like [this](https://github.com/openedx/openedx-filters/blob/96da9f887dfb8cf5834f562ad02493601ba263af/openedx_filters/learning/tests/test_filters.py#L219) one

2022-12-05 10:48 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +        return context
You're missing the filter exceptions like the existing filters: https://github.com/openedx/openedx-filters/blob/96da9f887dfb8cf5834f562ad02493601ba263af/openedx_filters/learning/filters.py#L70

2022-12-05 14:41 UTC, Henrrypg commented
Thank you @mariajgrimaldi, can you check with this changes?

2022-12-05 20:33 UTC, felipemontoya commented on openedx_filters/learning/filters.py
> +        """
I think this filter is quite useful for many applications. However I would also add the `RedirectToPage` exception that has been common to most other "RenderStarted" kind of filters.

2022-12-06 00:12 UTC, felipemontoya commented on openedx_filters/learning/filters.py
> +        """
Thanks @Henrrypg!
I see you removed the previous `PreventAccountSettingsRender`. That was good as well. I meant that you should also add the Redirect to Page.

@mariajgrimaldi Do you think it would be worth to refactor redirectToPage as a common exception that developers can inherit without having to override the __init__ every time?

2022-12-06 17:46 UTC, Henrrypg commented on openedx_filters/learning/filters.py
> +        """
@felipemontoya I see that we can have the same functionality with `RedirectToPage` than `PreventAccountSettingsRender` when we dont specify redirect url, How you can look it [in this example](https://github.com/eduNEXT/openedx-filters-samples/pull/1/files#diff-17ffcf8e28bec1e7ea5120567227998d9fb6f8967c309e02a5ffbb0ab22f9b17R778). You think that `PreventAccountSettingsRender` includes more use cases?

2022-12-06 19:58 UTC, felipemontoya commented on openedx_filters/learning/filters.py
> +        """
That might be true, but it would leave the sense that it is a hack instead of a well defined use case.
If we want users of this filter to stop the rendering and throw an error, they should raise `PreventAccountSettingsRender`. If they want to redirect, they raise `RedirectToPage`.
If we tell them that for stoping + show error they should send `RedirectToPage` but initialize it incompletely then it is a hackish solution.

2022-12-06 20:23 UTC, Henrrypg commented on openedx_filters/learning/filters.py
> +        """
With this point of view i'm completely with you @felipemontoya. I will add this exception again. Thanks!

2022-12-08 00:45 UTC, felipemontoya approved these changes
From my side, everything is covered. We are good to go.

2022-12-09 13:18 UTC, mariajgrimaldi commented
Please, add similar tests of those defined in this [test-suite](https://github.com/openedx/openedx-filters/blob/main/openedx_filters/learning/tests/test_filters.py#L269). That's why coverage is failing. Let me know if you need help :)

2022-12-19 11:54 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +            context (dict): context for the account settings page.
```suggestion
            context (dict): template context for the account settings page.
```

2022-12-19 11:58 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +
You're missing [this type](https://github.com/openedx/openedx-filters/blob/main/openedx_filters/learning/tests/test_filters.py#L88-L97) of unittest, that's probably why codecov is failing

2022-12-19 14:53 UTC, Henrrypg commented
Thank you @mariajgrimaldi, the test was added.

2022-12-20 11:29 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +        Custom class used to redirect before account settings rendering process.
```suggestion
        Custom class used to redirect before the account settings rendering process.
```

2022-12-20 11:30 UTC, mariajgrimaldi commented on openedx_filters/learning/tests/test_filters.py
> +        exception = AccountSettingsException(message="You can't access to this page", **attributes)
```suggestion
        exception = AccountSettingsException(message="You can't access this page", **attributes)
```

2022-12-20 11:36 UTC, mariajgrimaldi commented
I'll be testing this in conjunction the edx-platform PR.

2022-12-20 11:39 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +class AccountSettingsRenderStarted(OpenEdxPublicFilter):
is there a reason why the `RenderCustomResponse` is not being implemented?

2022-12-20 13:57 UTC, Henrrypg commented on openedx_filters/learning/filters.py
> +class AccountSettingsRenderStarted(OpenEdxPublicFilter):
There is no reason @mariajgrimaldi, i just forget to implement this kind of exception, i will work on this

2023-01-23 21:06 UTC, mphilbrick211 commented
Hi @Henrrypg! Just flagging that Maria has requested changes.

2023-01-24 20:51 UTC, Henrrypg commented
Hello @mariajgrimaldi @mphilbrick211

> is there a reason why the `RenderCustomResponse` is not being implemented?

About this change requested, i made it in [this commit](https://github.com/openedx/openedx-filters/pull/46/commits/6d91bf382e57be5acd47d6abf1695d3515165cf7). This PR was bloqued by https://github.com/openedx/edx-platform/pull/31295 but i just updated this one. :)

2023-01-31 14:11 UTC, mariajgrimaldi requested changes
Some minor comments :)

2023-01-31 14:11 UTC, mariajgrimaldi commented on openedx_filters/learning/tests/test_filters.py
> +    def test_halt_certificate_process(self, AccountSettingsException, attributes):
Shouldn't it be: `test_halt_account_rendering_process` ?

2023-01-31 14:11 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +            )
```suggestion
            super().__init__(message, response=response)
```

2023-01-31 14:11 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +
I see you already added it. Thanks!

2023-02-07 00:01 UTC, mphilbrick211 commented
Hi @Henrrypg - just checking to see if the requested changes were made and/or this pull request is ready for review. Thanks!

2023-02-20 19:43 UTC, mariajgrimaldi commented
I'll check on this again tomorrow! 

@Henrrypg: can you rebase with main? Thanks!

2023-02-21 22:14 UTC, mariajgrimaldi approved these changes
This looks good! Thanks for your patience and for following my suggestions!

2023-02-21 22:17 UTC, mariajgrimaldi commented
@Henrrypg: there are some issues with unittests. Can you help me fix them?

2023-02-21 22:20 UTC, Henrrypg commented
@mariajgrimaldi Of course, i'll work on this. Thank you!

2023-02-22 20:10 UTC, Henrrypg commented
@mariajgrimaldi  @mphilbrick211  can you please re run tests? :D

2023-02-28 18:26 UTC, mphilbrick211 commented
Hi @mariajgrimaldi! If this is good-to-go, do you mind merging?

2023-03-01 14:24 UTC, Henrrypg commented
Hi @mphilbrick211 @mariajgrimaldi, i just commited the changelog and bump version

2023-03-01 14:44 UTC, merged

2023-03-01 14:44 UTC, openedx-webhooks commented
@Henrrypg 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-filters&entry.867055334=https://github.com/openedx/openedx-filters/pull/46&entry.1484655318=https://github.com/Henrrypg&entry.752974735=2022-11-15+23:29&entry.1917517419=2023-03-01+14:44&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->