feat: adds the CourseEnrollmentSiteFilterRequested filter
openedx/openedx-filters pull request #47
Opened 2022-11-16 12:28 UTC by JuanDavidBuitrago

**Description:** 

This adds the ``CourseEnrollmentSiteFilterRequested`` filter which receive a Query Set context with enrollments information to allowing the filter pipeline to return the information that we need to filter.

An example of use is in [eox-tenant](https://github.com/eduNEXT/eox-tenant) custom filter step [pipeline](https://github.com/eduNEXT/eox-tenant/blob/master/eox_tenant/filters/pipeline.py), where it takes the enrollments information and is filtered by tenant request, returning only the enrollments in the current site for the user.

**JIRA:** N/A

**Dependencies:**

- https://github.com/openedx/edx-platform/pull/31331

**Merge deadline:** N/A

**Installation instructions:** 

Be sure to use ``edx-platform`` branch with changes https://github.com/openedx/edx-platform/pull/31331

**Testing instructions:**

The change can be tested with testing instructions in [eox-tenant plugin](https://github.com/eduNEXT/eox-tenant/pull/156).

**Reviewers:**
- [ ] @mariajgrimaldi 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** N/A

2022-11-16 12:28 UTC, openedx-webhooks commented
Thanks for the pull request, @JuanDavidBuitrago!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2022-11-25 13:21 UTC, JuanDavidBuitrago commented
Hi @mariajgrimaldi and @felipemontoya, could you help me review this?

2022-12-05 10:48 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +        return data.get("context")
You're missing the filter exceptions like the existing filters: https://github.com/openedx/openedx-filters/blob/96da9f887dfb8cf5834f562ad02493601ba263af/openedx_filters/learning/filters.py#L70

2022-12-16 22:46 UTC, JuanDavidBuitrago commented on openedx_filters/learning/filters.py
> +        return data.get("context")
I added filter exception

2022-12-16 22:51 UTC, JuanDavidBuitrago commented
Hi @mariajgrimaldi!!! 

Could you check again the last changes? Thanks!! :smiley:

2022-12-19 11:54 UTC, mariajgrimaldi requested changes

2022-12-19 11:54 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +        context (QuerySet): list of all user's course enrollments
If this is a queryset, then why is the argument called context?

2022-12-19 11:54 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +class CourseEnrollmentSiteFilterRequested(OpenEdxPublicFilter):
The other filters don't have the word _filter_ on them, can we remove it from here? 
Also, see how CourseEnrollmentRequested tells us the filter is executed before the course enrollment object is created, so we can stop the process or modify the object. We aim to follow that convention with each filter, can we try that here? Using the PR from edx-platform as an example of where you're using this filter, the name could be something like CourseEnrollmentQuerysetRequested (a bit long), do you have another suggestion?

2022-12-20 03:25 UTC, JuanDavidBuitrago commented on openedx_filters/learning/filters.py
> +        context (QuerySet): list of all user's course enrollments
I changed this to ``enrolments``.

2022-12-20 10:08 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +    Custom class used to filter user's course enrollments by site, when a request is made by the user.
Great description! The issue is that not many people will use this filter as described here. That type of documentation goes to the pipeline steps. I suggest something like: 
```suggestion
    Custom class used to create course enrollments queryset filters and its custom methods.
```
This following the other filters docstrings.

2022-12-20 10:08 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +    class PreventEnrollmentSiteFilter(OpenEdxFilterException):
It would help if you changed the name here too

2022-12-20 19:10 UTC, JuanDavidBuitrago commented on openedx_filters/learning/filters.py
> +    Custom class used to filter user's course enrollments by site, when a request is made by the user.
Thanks @mariajgrimaldi, I modified this part.

2022-12-20 19:13 UTC, JuanDavidBuitrago commented on openedx_filters/learning/filters.py
> +    class PreventEnrollmentSiteFilter(OpenEdxFilterException):
Yes, you're right. I forgot to change this.

Thanks for your comments. Could you check again?

2023-01-03 15:19 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +        Custom class used to stop the course enrollment queryset filter process.
`Custom class used to stop the course enrollment queryset request process.`

2023-01-03 15:20 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +        Custom class used to stop the course enrollment queryset filter process.
```suggestion
        Custom class used to stop the course enrollment queryset request process.
```

2023-01-03 15:25 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +    class PreventCourseEnrollmentQueryset(OpenEdxFilterException):
The wording here could be clearer. I like better: PreventEnrollmentQuerysetRequest, what do you folks think?

2023-01-05 19:52 UTC, JuanDavidBuitrago commented on openedx_filters/learning/filters.py
> +    class PreventCourseEnrollmentQueryset(OpenEdxFilterException):
It's ok, I agree with that. Let me know if you consider another change.

2023-01-12 15:17 UTC, mariajgrimaldi commented on openedx_filters/learning/tests/test_filters.py
> +
I think you're missing [this kind](https://github.com/openedx/openedx-filters/blob/main/openedx_filters/learning/tests/test_filters.py#L256) of tests. Could you add them please?

2023-01-18 12:58 UTC, JuanDavidBuitrago commented on openedx_filters/learning/tests/test_filters.py
> +
Thanks!! I added the test.

2023-01-18 14:41 UTC, mariajgrimaldi approved these changes
LGTM

2023-01-18 15:02 UTC, merged

2023-01-18 15:02 UTC, openedx-webhooks commented
@JuanDavidBuitrago 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-filters&entry.867055334=https://github.com/openedx/openedx-filters/pull/47&entry.1484655318=https://github.com/JuanDavidBuitrago&entry.752974735=2022-11-16+12:28&entry.1917517419=2023-01-18+15:02&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->