feat: adds VerticalBlockChildrenLoaded filter
openedx/openedx-filters pull request #52
Opened 2022-12-02 09:45 UTC by tecoholic

**Description:** 
This adds `VerticalBlockChildrenLoaded` filter that will be passed the list of the child blocks in a vertical block with the context and the view in which it would be rendered.

This would allow for adding/removing blocks in a Unit conditionally just before they are rendered into the view.

**JIRA:** Link to JIRA ticket

**Dependencies:** 
- https://github.com/openedx/edx-platform/pull/31388

**Merge deadline:**  None

**Installation instructions:** Nothing special

**Testing instructions:**

TODO

**Reviewers:**
- [ ] @navinkarkera 
- [ ]  @mariajgrimaldi 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

2022-12-02 09:46 UTC, openedx-webhooks commented
Thanks for the pull request, @tecoholic!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2022-12-21 11:03 UTC, navinkarkera commented
@tecoholic  Nice work! :+1:
- [x] I tested this: Tested the filter as described in https://github.com/openedx/edx-platform/pull/31388
- [x] I read through the code
- [ ] I checked for accessibility issues
- [x] Includes documentation
- [ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.

2022-12-27 23:19 UTC, mphilbrick211 commented
Flagging this for review @mariajgrimaldi :)

2022-12-30 22:45 UTC, mariajgrimaldi commented
I'm back on monday and I'll take a look at this. Sorry for the delay!

2023-01-03 15:17 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +class VerticalBlockRenderCompleted(OpenEdxPublicFilter):
Something I just noticed is both VerticalBlockChildRenderStarted and this filter are missing the exceptions like the ones defined in eg. [here](https://github.com/openedx/openedx-filters/pull/52/files#diff-0c79edd111d62405dc0829ac0b0b971c73b410de87c0133a7190b3de08b40ed9R354). Is there a reason for it?

2023-01-03 15:42 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +class VerticalBlockRenderCompleted(OpenEdxPublicFilter):
Then, when you implement those exceptions, you'll need to catch them in the edx-platform PR. You could follow [this implementation](https://github.com/openedx/edx-platform/blob/9a0fbe1a5758e80cd378b52bc93ef245ad458069/common/djangoapps/student/views/dashboard.py#L897) as a guide. You don't have to implement all exceptions, just the ones that make sense.

2023-01-03 15:44 UTC, mariajgrimaldi requested changes
I left a few comments regarding the missing exceptions. I missed those while reviewing https://github.com/openedx/openedx-filters/pull/38, so maybe we'll need to revisit that implementation as well. Let me know what you think.

2023-01-23 21:03 UTC, mphilbrick211 commented
Hi @tecoholic! Just following up on the changes Maria requested.

2023-01-26 08:56 UTC, tecoholic commented
@mphilbrick211 Hi, I was a bit busy last couple of weeks. Kindly expect updates to this PR this week. :)

2023-02-13 14:26 UTC, tecoholic commented
@mariajgrimaldi Hi, I have introduced exceptions for both the `VerticalBlockRenderCompleted` filter and the previous `VerticalBlockChildRenderStarted` filter and updated the PR. Can you kindly review this again?

2023-02-14 16:15 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +    class PreventVerticalBlockRender(OpenEdxFilterException):
I have a few questions here, but first I want to apologize for the missing documentation. I'm working on it, but it's been difficult to find time for it.

Alright, here are the questions:
1. Is this a filter that interacts with templates?
2. If that's true, which exceptions make sense to use? We've been using these:
- RenderInvalidComponent where component could be, eg. RenderInvalidDashboard: renders an error message, eg. you can't view this component
- RedirectToPage: redirects to a different page. Maybe you want to render a page hosted elsewhere. I don't think that one makes sense here. What do you think?
- RenderCustomResponse: render any other response. Like 404.

Which of those do you think would apply here?

2023-02-14 17:10 UTC, mariajgrimaldi commented
I tested this using the edx-platform PR and it works nicely! Thank you. @navinkarkera do you have any comments on this?

2023-02-15 07:13 UTC, navinkarkera commented
@mariajgrimaldi @tecoholic Looks good to me. We also have a sandbox demo which displays a form using this filter.

Sandbox:
- [URL](https://app.skilltagging.opencraft.hosting/learning/course/course-v1:edX+DemoX+Demo_Course/block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5/block-v1:edX+DemoX+Demo_Course+type@vertical+block@4f6c1b4e316a419ab5b6bf30e6c708e9)
- Login using staff credentials.
- Scroll to end of the page.

2023-02-15 12:51 UTC, tecoholic commented on openedx_filters/learning/filters.py
> +        """
@mariajgrimaldi I don't have any specific issues about moving this to a particular PR. But this is a part of the broader Skills Tagging project and I am not sure how project management would be affected because of it.

@navinkarkera Would creating a new ticket/PR for this be possible? Or should we use the same ticket and add an extra PR to it?

> There are others missing still,

Also, can you kindly elaborate on this? Is there a specific set of exceptions that must be present for all the filters?  From what I observed from the other filters, the exceptions seem to be very context specific. In this case of the `VerticalBlockChildRenderStarted` filter, I couldn't come up with any more scenarios that could be implemented by the filters. For example, an exception like "ReplaceBlock" won't be possible as that would require the filter to have access to the ModuleSystem that's rendering the XBlock and a lot more context that the filter won't have.

Similarly, for a the `VeriticalBlockRenderCompleted` hook, any changes that need to be done can only done to the output HTML Fragment and the reasonable exception scenario seems prevent the entire block, but other than that, I am finding it difficult to come up with any more exception scenarios.

2023-02-15 13:14 UTC, navinkarkera commented on openedx_filters/learning/filters.py
> +        """
@tecoholic We can use the same ticket and add the PR to it.

2023-02-15 13:57 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +        """
You're right about the exceptions! @tecoholic 
This PR can stay as it is. Thanks for talking through the suggestions!

2023-02-15 13:58 UTC, mariajgrimaldi approved these changes
@tecoholic @navinkarkera: this looks awesome! thanks for your hard work!
![image](https://user-images.githubusercontent.com/64440265/219046839-84f7a1ba-8d28-41a4-8c7a-36f9b749ce4e.png)

2023-02-15 13:59 UTC, mariajgrimaldi commented
@tecoholic @navinkarkera: is this ready for merging?

2023-02-15 14:17 UTC, mariajgrimaldi commented
@tecoholic: just one last thing, can you please update the changelog? Thanks!

2023-02-16 14:41 UTC, tecoholic commented
@mariajgrimaldi  Thank you for your time and the review. I have added the changes to the changelog and bumped the version. The CI seems to be failing due to a [Codecov token issue](https://github.com/openedx/openedx-filters/actions/runs/4195061648/jobs/7274062381#step:7:53). Other than that I think we are all good. Kindly merge and release at your convenience. :tada:

2023-02-16 19:38 UTC, mariajgrimaldi commented
@tecoholic: hi again! can you rebase with master? I merged a PR updating the codecov version!

2023-02-17 07:57 UTC, tecoholic commented
@mariajgrimaldi Done. And all checks seem to be passing.

2023-02-17 13:45 UTC, merged

2023-02-17 13:45 UTC, openedx-webhooks commented
@tecoholic 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-filters&entry.867055334=https://github.com/openedx/openedx-filters/pull/52&entry.1484655318=https://github.com/tecoholic&entry.752974735=2022-12-02+09:45&entry.1917517419=2023-02-17+13:45&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->

2023-02-17 13:55 UTC, mariajgrimaldi commented
@tecoholic: new release is out!