feat: adds TenantAwareLinkRenderStarted filter
openedx/openedx-filters pull request #77
Opened 2023-03-30 11:31 UTC by JuanDavidBuitrago

**Description:** 

This adds the ``TenantAwareLinkRenderStarted`` filter which receive a string context with LMS url to allowing the filter pipeline to return the information that we need to filter, in this case a tenant aware link from Studio to LMS.

An example of use is in [eox-tenant](https://github.com/eduNEXT/eox-tenant) custom filter step [pipeline](https://github.com/eduNEXT/eox-tenant/blob/master/eox_tenant/filters/pipeline.py), where it takes the LMS_ROOT_URL and return only the tenant aware link in the respective site.

**JIRA:** N/A

**Dependencies:**

- https://github.com/openedx/edx-platform/pull/32014

**Merge deadline:** N/A

**Installation instructions:** 

Be sure to use ``edx-platform`` branch with changes https://github.com/openedx/edx-platform/pull/32014

**Testing instructions:**

The change can be tested with testing instructions in [eox-tenant plugin](https://github.com/eduNEXT/eox-tenant/pull/156).

**Reviewers:**
- [ ] @mariajgrimaldi
- [ ] @felipemontoya 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** N/A

2023-04-04 00:15 UTC, mphilbrick211 commented
Hi @mariajgrimaldi - would you mind reviewing and merging if all looks good to you? Thanks!

2023-04-17 22:10 UTC, mariajgrimaldi commented
Can you update the PR with the latest name changes? @JuanDavidBuitrago, please! FYI: I'll review this PR and the edx-platform one this week.

2023-05-10 18:38 UTC, mphilbrick211 commented
Hi @JuanDavidBuitrago! Would you mind taking a look at the branch conflicts?

CC @mariajgrimaldi for review.

2023-05-16 02:39 UTC, MaferMazu commented
@mariajgrimaldi, can you help us with a review?

2023-06-01 14:16 UTC, mariajgrimaldi requested changes
I understand these changes are useful to your initiative. The issue is that this needs to be useful as well for the community, can you make it a bit less specific? The community might not use eox-tenant or even need a tenant aware modification, how would you rebrand this modification so it's more general?

2023-06-26 14:35 UTC, JuanDavidBuitrago commented
Hi @mphilbrick211 I'm going to work on it in this week

2023-07-17 22:44 UTC, mphilbrick211 commented
Hi @JuanDavidBuitrago! Just following-up on this :)

2023-07-18 18:53 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +    filter_type = "org.openedx.learning.tenant_aware_link.render.started.v1"
According to your edx-platform PR, I think we could rebrand this filter by using what you're currently using it for. It could be called:
`org.openedx.learning.asset.render.started.v1`
And given that this filter would affect course staff only, then I'm not sure the correct subdomain is `learning`. Give this page a read for more info on subdomains: https://openedx.atlassian.net/wiki/spaces/AC/pages/663224968/edX+DDD+Bounded+Contexts

2023-08-22 18:28 UTC, mphilbrick211 commented
hi @JuanDavidBuitrago! Just checking in to see if you plan to pursue this pull request? Please let us know. Thanks!

2023-09-07 14:26 UTC, mariajgrimaldi commented
@mphilbrick211: I spoke internally with @JuanDavidBuitrago's team, and they told me they didn't have the capacity to take this on right now. I'll move this PR to draft to give them time to work on it. Thanks!

2024-02-20 21:33 UTC, mphilbrick211 commented
Hi @JuanDavidBuitrago! I'm going to close this pull request for now. We can reopen when you're ready to pursue. Thanks!

2024-02-20 21:33 UTC, closed without merging

2024-02-20 21:33 UTC, openedx-webhooks commented
@JuanDavidBuitrago Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-filters&entry.867055334=https://github.com/openedx/openedx-filters/pull/77&entry.1484655318=https://github.com/JuanDavidBuitrago&entry.752974735=2023-03-30+11:31&entry.1917517419=2024-02-20+21:33&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->